[project]
name = "ohclink-api"
version = "0.1.0"
description = ""
authors = [
    {name = "onehunnitconst",email = "skygana@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.123.10,<0.124.0)",
    "uvicorn[standard] (>=0.38.0,<0.39.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)"
]

[project.scripts]
app = "ohclink_api.cli:main"

[tool.poetry]
packages = [{include = "ohclink_api", from = "src"}]

[tool.poetry.scripts]
app = "ohclink_api.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
